'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import {
  BookOpen,
  CalendarCheck2,
  Eye,
  Pencil,
  Plus,
  Printer,
  Search,
  Trash2,
  Wallet,
  X,
} from 'lucide-react';
import { AcademyCourse, AcademyReceipt, AcademyStudent, AuthUser } from '@/types';
import {
  AcademyStudentInput,
  createAcademyStudent,
  deleteAcademyStudent,
  getAcademyStudents,
  updateAcademyStudent,
} from '@/services/academyStudentService';
import { getAcademyCourses } from '@/services/academyCourseService';
import { getAcademyReceipts } from '@/services/academyReceiptService';
import { getStudentProfileData } from '@/services/academyDashboardService';

interface AcademyStudentsPanelProps {
  user: AuthUser;
  onNavigate: (navId: string) => void;
}

interface StudentFormState extends AcademyStudentInput {}

const emptyForm: StudentFormState = {
  studentName: '',
  parentName: '',
  phone: '',
  email: '',
  address: '',
  dateOfBirth: '',
  admissionDate: new Date().toISOString().slice(0, 10),
  notes: '',
  status: 'active',
  selectedCourses: [],
};

function formatCurrency(amount: number) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

function calculateAttendancePercentage(total: number, present: number, late: number) {
  if (total === 0) return 0;
  return Math.round(((present + late) / total) * 100);
}

function printReceipt(receipt: AcademyReceipt) {
  const receiptWindow = window.open('', '_blank', 'width=920,height=760');
  if (!receiptWindow) {
    toast.error('Popup blocked. Please allow popups to print receipts.');
    return;
  }

  receiptWindow.document.write(`
    <html>
      <head>
        <title>Receipt ${receipt.receiptNumber}</title>
        <style>
          body { font-family: Arial, sans-serif; color: #111827; margin: 0; }
          .receipt { max-width: 820px; margin: 24px auto; padding: 32px; }
          .card { border: 1px solid #dbe3f0; border-radius: 18px; padding: 28px; }
          .header { display: flex; justify-content: space-between; gap: 24px; margin-bottom: 28px; }
          .brand { font-size: 28px; font-weight: 700; color: #4338ca; }
          .muted { color: #64748b; font-size: 13px; }
          .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; margin-top: 18px; }
          .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 6px; }
          .value { font-size: 14px; font-weight: 600; color: #111827; }
          .summary { margin-top: 24px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
          .summary-row { display: flex; justify-content: space-between; margin-bottom: 10px; font-size: 14px; }
          .signature { margin-top: 40px; display: flex; justify-content: space-between; align-items: end; }
          @media print {
            body { margin: 0; }
          }
        </style>
      </head>
      <body>
        <div class="receipt">
          <div class="card">
            <div class="header">
              <div>
                <div class="brand">${receipt.businessName}</div>
                <div class="muted">${receipt.businessAddress || ''}</div>
                <div class="muted">${receipt.businessPhone || ''}</div>
              </div>
              <div>
                <div class="label">Receipt Number</div>
                <div class="value">${receipt.receiptNumber}</div>
                <div class="label" style="margin-top: 14px;">Payment Date</div>
                <div class="value">${receipt.paymentDate}</div>
              </div>
            </div>
            <div class="grid">
              <div><div class="label">Student Name</div><div class="value">${receipt.studentName}</div></div>
              <div><div class="label">Course</div><div class="value">${receipt.courseName}</div></div>
              <div><div class="label">Payment Mode</div><div class="value">${receipt.paymentMode}</div></div>
              <div><div class="label">Receipt ID</div><div class="value">${receipt.receiptId}</div></div>
            </div>
            <div class="summary">
              <div class="summary-row"><span>Amount Paid</span><strong>${formatCurrency(receipt.amountPaid)}</strong></div>
              <div class="summary-row"><span>Pending Amount</span><strong>${formatCurrency(receipt.pendingAmount)}</strong></div>
            </div>
            <div class="signature">
              <div class="muted">Generated by BizManage</div>
              <div>
                <div class="muted">Authorized Signature</div>
                <div style="width: 180px; border-top: 1px solid #111827; margin-top: 32px;"></div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  `);

  receiptWindow.document.close();
  receiptWindow.focus();
  receiptWindow.print();
}

export default function AcademyStudentsPanel({ user, onNavigate }: AcademyStudentsPanelProps) {
  const [students, setStudents] = useState<AcademyStudent[]>([]);
  const [courses, setCourses] = useState<AcademyCourse[]>([]);
  const [receiptCounts, setReceiptCounts] = useState<Map<string, number>>(new Map());
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | AcademyStudent['status']>('all');
  const [page, setPage] = useState(1);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingStudent, setEditingStudent] = useState<AcademyStudent | null>(null);
  const [form, setForm] = useState<StudentFormState>(emptyForm);
  const [saving, setSaving] = useState(false);
  const [profileStudent, setProfileStudent] = useState<AcademyStudent | null>(null);
  const [profileData, setProfileData] = useState<Awaited<ReturnType<typeof getStudentProfileData>> | null>(null);
  const [profileTab, setProfileTab] = useState<'overview' | 'courses' | 'fees' | 'receipts' | 'attendance'>('overview');

  useEffect(() => {
    let active = true;
    setLoading(true);

    Promise.all([getAcademyStudents(user.id), getAcademyCourses(user.id), getAcademyReceipts(user.id)])
      .then(([studentData, courseData, receipts]) => {
        if (!active) return;
        setStudents(studentData);
        setCourses(courseData.filter((course) => course.status === 'active'));
        const counts = new Map<string, number>();
        receipts.forEach((receipt) => {
          counts.set(receipt.studentId, (counts.get(receipt.studentId) ?? 0) + 1);
        });
        setReceiptCounts(counts);
      })
      .catch(() => {
        if (!active) return;
        toast.error('Unable to load academy students right now.');
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, [user.id]);

  const filteredStudents = useMemo(() => {
    const query = search.trim().toLowerCase();
    return students.filter((student) => {
      const matchesStatus = statusFilter === 'all' || student.status === statusFilter;
      const matchesQuery =
        query.length === 0 ||
        [
          student.admissionId,
          student.studentName,
          student.parentName,
          student.phone,
          student.email,
        ]
          .join(' ')
          .toLowerCase()
          .includes(query);
      return matchesStatus && matchesQuery;
    });
  }, [search, statusFilter, students]);

  const paginatedStudents = useMemo(() => {
    const start = (page - 1) * 10;
    return filteredStudents.slice(start, start + 10);
  }, [filteredStudents, page]);

  const totalPages = Math.max(1, Math.ceil(filteredStudents.length / 10));

  useEffect(() => {
    setPage(1);
  }, [search, statusFilter]);

  const toggleCourse = useCallback((course: AcademyCourse) => {
    setForm((current) => {
      const exists = current.selectedCourses.some((item) => item.courseId === course.courseId);
      return {
        ...current,
        selectedCourses: exists
          ? current.selectedCourses.filter((item) => item.courseId !== course.courseId)
          : [
              ...current.selectedCourses,
              {
                courseId: course.courseId,
                courseName: course.courseName,
                fees: course.fees,
              },
            ],
      };
    });
  }, []);

  const openCreateModal = useCallback(() => {
    setEditingStudent(null);
    setForm(emptyForm);
    setIsModalOpen(true);
  }, []);

  const openEditModal = useCallback(
    (student: AcademyStudent) => {
      setEditingStudent(student);
      const selectedCourses = courses
        .filter((course) => student.enrolledCourseIds.includes(course.courseId))
        .map((course) => ({
          courseId: course.courseId,
          courseName: course.courseName,
          fees: course.fees,
        }));
      setForm({
        studentName: student.studentName,
        parentName: student.parentName,
        phone: student.phone,
        email: student.email,
        address: student.address,
        dateOfBirth: student.dateOfBirth,
        admissionDate: student.admissionDate,
        notes: student.notes,
        status: student.status,
        selectedCourses,
      });
      setIsModalOpen(true);
    },
    [courses]
  );

  const closeModal = useCallback(() => {
    setEditingStudent(null);
    setForm(emptyForm);
    setIsModalOpen(false);
  }, []);

  const handleSubmit = useCallback(
    async (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      setSaving(true);

      try {
        if (editingStudent) {
          await updateAcademyStudent(user.id, editingStudent.id, {
            ...form,
            paidFees: editingStudent.paidFees,
          });
          setStudents(await getAcademyStudents(user.id));
          toast.success('Student updated successfully.');
        } else {
          await createAcademyStudent(user.id, form);
          setStudents(await getAcademyStudents(user.id));
          toast.success('Student added successfully.');
        }
        closeModal();
      } catch (caught) {
        toast.error(caught instanceof Error ? caught.message : 'Unable to save student.');
      } finally {
        setSaving(false);
      }
    },
    [closeModal, editingStudent, form, user.id]
  );

  const handleDelete = useCallback(
    async (student: AcademyStudent) => {
      const confirmed = window.confirm(`Delete ${student.studentName}?`);
      if (!confirmed) return;
      try {
        await deleteAcademyStudent(user.id, student.id);
        setStudents(await getAcademyStudents(user.id));
        toast.success('Student deleted successfully.');
      } catch {
        toast.error('Unable to delete student right now.');
      }
    },
    [user.id]
  );

  const openProfile = useCallback(async (student: AcademyStudent) => {
    setProfileStudent(student);
    setProfileTab('overview');
    const data = await getStudentProfileData(user.id, student.studentId);
    setProfileData(data);
  }, [user.id]);

  const closeProfile = useCallback(() => {
    setProfileStudent(null);
    setProfileData(null);
  }, []);

  const handleAddFee = useCallback((student: AcademyStudent) => {
    window.sessionStorage.setItem('academy:selectedStudentId', student.studentId);
    onNavigate('nav-fees');
  }, [onNavigate]);

  const handleAttendance = useCallback((student: AcademyStudent) => {
    window.sessionStorage.setItem('academy:selectedStudentId', student.studentId);
    onNavigate('nav-attendance');
  }, [onNavigate]);

  const handlePrintLatestReceipt = useCallback(async (student: AcademyStudent) => {
    const data = await getStudentProfileData(user.id, student.studentId);
    const latestReceipt = data.receipts[0];
    if (!latestReceipt) {
      toast.error('No receipts found for this student yet.');
      return;
    }
    printReceipt(latestReceipt);
  }, [user.id]);

  return (
    <div className="max-w-screen-2xl mx-auto space-y-6">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-700 uppercase tracking-[0.24em] text-primary">Academy Students</p>
          <h1 className="mt-1 text-2xl font-700 text-foreground">Students</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Admissions, enrollments, fee summary, receipt access, and attendance history.
          </p>
        </div>
        <button
          type="button"
          onClick={openCreateModal}
          className="btn-primary inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm"
        >
          <Plus size={16} />
          Add Student
        </button>
      </div>

      <div className="glass-card rounded-2xl border border-border overflow-hidden">
        <div className="flex flex-col gap-4 border-b border-border p-5 lg:flex-row lg:items-center lg:justify-between">
          <div className="relative flex-1">
            <Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search by name, phone, email, parent name, or admission ID"
              className="w-full rounded-xl border border-border bg-input py-3 pl-11 pr-4 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <select
            value={statusFilter}
            onChange={(event) => setStatusFilter(event.target.value as 'all' | AcademyStudent['status'])}
            className="rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="all">All statuses</option>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
        </div>

        {loading ? (
          <div className="p-16 text-center text-muted-foreground">Loading students...</div>
        ) : filteredStudents.length === 0 ? (
          <div className="px-5 py-16 text-center">
            <p className="text-sm font-600 text-foreground">
              No students yet. Add your first student to start managing admissions.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-[1200px] w-full text-left text-sm">
              <thead className="bg-muted/80 text-xs uppercase tracking-wider text-muted-foreground">
                <tr>
                  <th className="px-5 py-4">Admission ID</th>
                  <th className="px-5 py-4">Student Name</th>
                  <th className="px-5 py-4">Parent Name</th>
                  <th className="px-5 py-4">Phone</th>
                  <th className="px-5 py-4">Courses Enrolled</th>
                  <th className="px-5 py-4">Total Fees</th>
                  <th className="px-5 py-4">Paid Fees</th>
                  <th className="px-5 py-4">Pending Fees</th>
                  <th className="px-5 py-4">Status</th>
                  <th className="px-5 py-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border bg-white">
                {paginatedStudents.map((student) => (
                  <tr key={student.id}>
                    <td className="px-5 py-4 text-muted-foreground">{student.admissionId}</td>
                    <td className="px-5 py-4">
                      <p className="font-600 text-foreground">{student.studentName}</p>
                      <p className="mt-1 text-xs text-muted-foreground">{student.email}</p>
                    </td>
                    <td className="px-5 py-4 text-muted-foreground">{student.parentName}</td>
                    <td className="px-5 py-4 text-muted-foreground">{student.phone}</td>
                    <td className="px-5 py-4 text-muted-foreground">{student.enrolledCourseIds.length}</td>
                    <td className="px-5 py-4 text-muted-foreground">{formatCurrency(student.totalFees)}</td>
                    <td className="px-5 py-4 text-muted-foreground">{formatCurrency(student.paidFees)}</td>
                    <td className="px-5 py-4 text-muted-foreground">{formatCurrency(student.pendingFees)}</td>
                    <td className="px-5 py-4">
                      <span className={`inline-flex rounded-full px-3 py-1 text-xs font-600 ${student.status === 'active' ? 'badge-success' : 'badge-neutral'}`}>
                        {student.status}
                      </span>
                    </td>
                    <td className="px-5 py-4">
                      <div className="flex justify-end gap-2">
                        <button type="button" onClick={() => openProfile(student)} className="btn-outline rounded-xl px-3 py-2 text-xs"><Eye size={14} /></button>
                        <button type="button" onClick={() => openEditModal(student)} className="btn-outline rounded-xl px-3 py-2 text-xs"><Pencil size={14} /></button>
                        <button type="button" onClick={() => handleAddFee(student)} className="btn-outline rounded-xl px-3 py-2 text-xs"><Wallet size={14} /></button>
                        <button type="button" onClick={() => handleAttendance(student)} className="btn-outline rounded-xl px-3 py-2 text-xs"><CalendarCheck2 size={14} /></button>
                        <button
                          type="button"
                          disabled={!receiptCounts.get(student.studentId)}
                          onClick={() => handlePrintLatestReceipt(student)}
                          className="btn-outline rounded-xl px-3 py-2 text-xs disabled:cursor-not-allowed disabled:opacity-50"
                        >
                          <Printer size={14} />
                        </button>
                        <button type="button" onClick={() => handleDelete(student)} className="rounded-xl border border-danger/25 bg-danger/5 px-3 py-2 text-xs text-danger transition hover:bg-danger/10"><Trash2 size={14} /></button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {!loading && filteredStudents.length > 0 && (
          <div className="flex items-center justify-between border-t border-border bg-white/80 px-5 py-4">
            <p className="text-xs text-muted-foreground">
              Showing {(page - 1) * 10 + 1}-{Math.min(page * 10, filteredStudents.length)} of {filteredStudents.length} students
            </p>
            <div className="flex items-center gap-2">
              <button type="button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1} className="btn-outline rounded-xl px-3 py-2 text-xs disabled:cursor-not-allowed disabled:opacity-50">
                Prev
              </button>
              <span className="rounded-lg bg-muted px-3 py-2 text-xs font-600 text-foreground">
                {page} / {totalPages}
              </span>
              <button type="button" onClick={() => setPage((current) => Math.min(totalPages, current + 1))} disabled={page === totalPages} className="btn-outline rounded-xl px-3 py-2 text-xs disabled:cursor-not-allowed disabled:opacity-50">
                Next
              </button>
            </div>
          </div>
        )}
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm">
          <div className="mx-auto mt-8 max-w-4xl overflow-hidden rounded-[28px] border border-border bg-white shadow-card">
            <div className="flex items-center justify-between border-b border-border px-6 py-5">
              <div>
                <p className="text-xs font-700 uppercase tracking-[0.22em] text-primary">
                  {editingStudent ? 'Edit Student' : 'New Admission'}
                </p>
                <h2 className="mt-1 text-xl font-700 text-foreground">
                  {editingStudent ? 'Update student profile' : 'Add student'}
                </h2>
              </div>
              <button type="button" onClick={closeModal} className="rounded-full bg-muted p-2 text-muted-foreground">
                <X size={18} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="grid gap-4 p-6 md:grid-cols-2">
              {[
                ['Student Name', 'studentName'],
                ['Parent Name', 'parentName'],
                ['Phone', 'phone'],
                ['Email', 'email'],
              ].map(([label, key]) => (
                <div key={key}>
                  <label className="mb-1.5 block text-sm font-600 text-foreground">{label}</label>
                  <input
                    required={key !== 'email'}
                    type={key === 'email' ? 'email' : 'text'}
                    value={form[key as keyof StudentFormState] as string}
                    onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))}
                    className="w-full rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                </div>
              ))}
              <div className="md:col-span-2">
                <label className="mb-1.5 block text-sm font-600 text-foreground">Address</label>
                <input
                  value={form.address}
                  onChange={(event) => setForm((current) => ({ ...current, address: event.target.value }))}
                  className="w-full rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-600 text-foreground">Admission Date</label>
                <input
                  required
                  type="date"
                  value={form.admissionDate}
                  onChange={(event) => setForm((current) => ({ ...current, admissionDate: event.target.value }))}
                  className="w-full rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-600 text-foreground">Date of Birth</label>
                <input
                  type="date"
                  value={form.dateOfBirth}
                  onChange={(event) => setForm((current) => ({ ...current, dateOfBirth: event.target.value }))}
                  className="w-full rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
              <div className="md:col-span-2">
                <label className="mb-1.5 block text-sm font-600 text-foreground">Select Courses</label>
                <div className="grid gap-3 rounded-2xl border border-border bg-muted/30 p-4 sm:grid-cols-2">
                  {courses.map((course) => {
                    const selected = form.selectedCourses.some((item) => item.courseId === course.courseId);
                    return (
                      <button
                        key={course.id}
                        type="button"
                        onClick={() => toggleCourse(course)}
                        className={`rounded-2xl border px-4 py-3 text-left transition ${selected ? 'border-primary bg-indigo-50' : 'border-border bg-white'}`}
                      >
                        <p className="font-600 text-foreground">{course.courseName}</p>
                        <p className="mt-1 text-xs text-muted-foreground">
                          {course.duration} · {formatCurrency(course.fees)}
                        </p>
                      </button>
                    );
                  })}
                </div>
              </div>
              <div className="md:col-span-2">
                <label className="mb-1.5 block text-sm font-600 text-foreground">Notes</label>
                <textarea
                  rows={4}
                  value={form.notes}
                  onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))}
                  className="w-full resize-none rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
              <div className="md:col-span-2">
                <label className="mb-1.5 block text-sm font-600 text-foreground">Status</label>
                <select
                  value={form.status}
                  onChange={(event) => setForm((current) => ({ ...current, status: event.target.value as AcademyStudent['status'] }))}
                  className="w-full rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                >
                  <option value="active">Active</option>
                  <option value="inactive">Inactive</option>
                </select>
              </div>
              <div className="md:col-span-2 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
                <button type="button" onClick={closeModal} className="btn-outline rounded-xl px-5 py-3 text-sm">
                  Cancel
                </button>
                <button type="submit" disabled={saving} className="btn-primary rounded-xl px-5 py-3 text-sm disabled:cursor-not-allowed disabled:opacity-60">
                  {saving ? 'Saving...' : editingStudent ? 'Update Student' : 'Add Student'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {profileStudent && profileData && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm">
          <div className="ml-auto max-w-4xl rounded-[28px] border border-border bg-white shadow-card">
            <div className="flex items-center justify-between border-b border-border px-6 py-5">
              <div>
                <p className="text-xs font-700 uppercase tracking-[0.22em] text-primary">Student Profile</p>
                <h2 className="mt-1 text-xl font-700 text-foreground">{profileStudent.studentName}</h2>
              </div>
              <button type="button" onClick={closeProfile} className="rounded-full bg-muted p-2 text-muted-foreground">
                <X size={18} />
              </button>
            </div>

            <div className="flex flex-wrap gap-2 border-b border-border px-6 py-4">
              {(['overview', 'courses', 'fees', 'receipts', 'attendance'] as const).map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setProfileTab(tab)}
                  className={`rounded-full px-4 py-2 text-sm font-600 ${profileTab === tab ? 'bg-indigo-50 text-primary' : 'bg-muted/60 text-muted-foreground'}`}
                >
                  {tab === 'fees' ? 'Fee History' : tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>

            <div className="p-6">
              {profileTab === 'overview' && (() => {
                const totalAttendance = profileData.attendance.length;
                const presentCount = profileData.attendance.filter((item) => item.status === 'present').length;
                const lateCount = profileData.attendance.filter((item) => item.status === 'late').length;
                return (
                  <div className="grid gap-5 md:grid-cols-2">
                    <div className="rounded-2xl border border-border p-5">
                      <p className="text-sm font-700 text-foreground">Student Details</p>
                      <div className="mt-4 space-y-3 text-sm text-muted-foreground">
                        <p><span className="font-600 text-foreground">Admission ID:</span> {profileStudent.admissionId}</p>
                        <p><span className="font-600 text-foreground">Parent:</span> {profileStudent.parentName}</p>
                        <p><span className="font-600 text-foreground">Phone:</span> {profileStudent.phone}</p>
                        <p><span className="font-600 text-foreground">Email:</span> {profileStudent.email}</p>
                        <p><span className="font-600 text-foreground">Address:</span> {profileStudent.address || '—'}</p>
                      </div>
                    </div>
                    <div className="rounded-2xl border border-border p-5">
                      <p className="text-sm font-700 text-foreground">Fee & Attendance Summary</p>
                      <div className="mt-4 space-y-3 text-sm text-muted-foreground">
                        <p><span className="font-600 text-foreground">Total Fees:</span> {formatCurrency(profileStudent.totalFees)}</p>
                        <p><span className="font-600 text-foreground">Paid Fees:</span> {formatCurrency(profileStudent.paidFees)}</p>
                        <p><span className="font-600 text-foreground">Pending Fees:</span> {formatCurrency(profileStudent.pendingFees)}</p>
                        <p><span className="font-600 text-foreground">Attendance Percentage:</span> {calculateAttendancePercentage(totalAttendance, presentCount, lateCount)}%</p>
                      </div>
                    </div>
                  </div>
                );
              })()}

              {profileTab === 'courses' && (
                <div className="space-y-3">
                  {profileData.enrollments.length ? profileData.enrollments.map((enrollment) => (
                    <div key={enrollment.id} className="rounded-2xl border border-border p-4">
                      <p className="font-600 text-foreground">{String(enrollment.courseName ?? '')}</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Enrolled: {String(enrollment.enrollmentDate ?? '')} · Status: {String(enrollment.status ?? '')}
                      </p>
                    </div>
                  )) : <p className="text-sm text-muted-foreground">No enrollments found.</p>}
                </div>
              )}

              {profileTab === 'fees' && (
                <div className="space-y-3">
                  {profileData.fees.length ? profileData.fees.map((fee) => (
                    <div key={fee.id} className="rounded-2xl border border-border p-4">
                      <p className="font-600 text-foreground">{fee.courseName}</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        Paid {formatCurrency(fee.paidAmount)} · Pending {formatCurrency(fee.pendingAmount)} · {fee.paymentMode} · {fee.paymentDate}
                      </p>
                    </div>
                  )) : <p className="text-sm text-muted-foreground">No fee history found.</p>}
                </div>
              )}

              {profileTab === 'receipts' && (
                <div className="space-y-3">
                  {profileData.receipts.length ? profileData.receipts.map((receipt) => (
                    <div key={receipt.id} className="flex items-center justify-between rounded-2xl border border-border p-4">
                      <div>
                        <p className="font-600 text-foreground">{receipt.receiptNumber}</p>
                        <p className="mt-1 text-sm text-muted-foreground">
                          {receipt.courseName} · {formatCurrency(receipt.amountPaid)} · {receipt.paymentDate}
                        </p>
                      </div>
                      <button type="button" onClick={() => printReceipt(receipt)} className="btn-outline rounded-xl px-4 py-2 text-xs">
                        Print Receipt
                      </button>
                    </div>
                  )) : <p className="text-sm text-muted-foreground">No receipts found.</p>}
                </div>
              )}

              {profileTab === 'attendance' && (
                <div className="space-y-3">
                  {profileData.attendance.length ? profileData.attendance.map((record) => (
                    <div key={record.id} className="rounded-2xl border border-border p-4">
                      <p className="font-600 text-foreground">{record.courseName}</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        {record.attendanceDate} · {record.status} · {record.remarks || 'No remarks'}
                      </p>
                    </div>
                  )) : <p className="text-sm text-muted-foreground">No attendance history found.</p>}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
