'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { Download, Eye, Printer, Search } from 'lucide-react';
import { AcademyPaymentMode, AcademyReceipt, AuthUser } from '@/types';
import { getAcademyReceipts } from '@/services/academyReceiptService';
import RetryState from '@/components/ui/RetryState';
import { useSlowLoading } from '@/hooks/useSlowLoading';
import { useDebouncedValue } from '@/hooks/useDebouncedValue';

interface AcademyReceiptsPanelProps {
  user: AuthUser;
  onNavigate: (navId: string) => void;
}

function formatCurrency(amount: number) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

function printReceipt(receipt: AcademyReceipt) {
  const receiptWindow = window.open('', '_blank', 'width=920,height=760');
  if (!receiptWindow) {
    toast.error('Popup blocked. Please allow popups to print receipts.');
    return;
  }

  receiptWindow.document.write(`
    <html>
      <head>
        <title>${receipt.receiptNumber}</title>
        <style>
          body { font-family: Arial, sans-serif; color: #111827; margin: 0; background: #f8fafc; }
          .shell { max-width: 820px; margin: 24px auto; padding: 24px; }
          .card { background: white; border: 1px solid #dbe3f0; border-radius: 18px; padding: 28px; }
          .row { display: flex; justify-content: space-between; gap: 24px; }
          .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; margin-top: 24px; }
          .label { color: #64748b; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 6px; }
          .value { color: #0f172a; font-size: 14px; font-weight: 600; }
          .brand { color: #4338ca; font-size: 28px; font-weight: 700; }
          .summary { margin-top: 24px; padding-top: 18px; border-top: 1px solid #e5e7eb; }
          .summary-row { display: flex; justify-content: space-between; margin-bottom: 10px; font-size: 14px; }
          .footer { margin-top: 40px; display: flex; justify-content: space-between; align-items: end; }
          .muted { color: #64748b; font-size: 13px; }
          @media print {
            body { background: white; }
            .shell { margin: 0 auto; }
          }
        </style>
      </head>
      <body>
        <div class="shell">
          <div class="card">
            <div class="row">
              <div>
                <div class="brand">${receipt.businessName}</div>
                <div class="muted">${receipt.businessAddress || ''}</div>
                <div class="muted">${receipt.businessPhone || ''}</div>
              </div>
              <div>
                <div class="label">Receipt Number</div>
                <div class="value">${receipt.receiptNumber}</div>
                <div class="label" style="margin-top: 14px;">Payment Date</div>
                <div class="value">${receipt.paymentDate}</div>
              </div>
            </div>
            <div class="grid">
              <div><div class="label">Student Name</div><div class="value">${receipt.studentName}</div></div>
              <div><div class="label">Course</div><div class="value">${receipt.courseName}</div></div>
              <div><div class="label">Payment Mode</div><div class="value">${receipt.paymentMode}</div></div>
              <div><div class="label">Receipt ID</div><div class="value">${receipt.receiptId}</div></div>
            </div>
            <div class="summary">
              <div class="summary-row"><span>Amount Paid</span><strong>${formatCurrency(receipt.amountPaid)}</strong></div>
              <div class="summary-row"><span>Pending Amount</span><strong>${formatCurrency(receipt.pendingAmount)}</strong></div>
            </div>
            <div class="footer">
              <div class="muted">Generated by BizManage</div>
              <div>
                <div class="muted">Authorized Signature</div>
                <div style="width: 180px; border-top: 1px solid #111827; margin-top: 32px;"></div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  `);
  receiptWindow.document.close();
  receiptWindow.focus();
  receiptWindow.print();
}

export default function AcademyReceiptsPanel({ user }: AcademyReceiptsPanelProps) {
  const [receipts, setReceipts] = useState<AcademyReceipt[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [modeFilter, setModeFilter] = useState<'all' | AcademyPaymentMode>('all');
  const [selectedReceipt, setSelectedReceipt] = useState<AcademyReceipt | null>(null);
  const [retryKey, setRetryKey] = useState(0);
  const debouncedSearch = useDebouncedValue(search, 250);
  const { showSlowMessage, showRetry } = useSlowLoading(loading);

  useEffect(() => {
    let active = true;
    setLoading(true);

    getAcademyReceipts(user.id)
      .then((data) => {
        if (!active) return;
        setReceipts(data);
      })
      .catch(() => {
        if (!active) return;
        toast.error('Unable to load receipts right now.');
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, [retryKey, user.id]);

  const filteredReceipts = useMemo(() => {
    const query = debouncedSearch.trim().toLowerCase();
    return receipts.filter((receipt) => {
      const matchesMode = modeFilter === 'all' || receipt.paymentMode === modeFilter;
      const matchesQuery =
        query.length === 0 ||
        [
          receipt.receiptNumber,
          receipt.studentName,
          receipt.courseName,
          receipt.paymentDate,
          receipt.paymentMode,
        ]
          .join(' ')
          .toLowerCase()
          .includes(query);
      return matchesMode && matchesQuery;
    });
  }, [debouncedSearch, modeFilter, receipts]);

  const handleDownloadPlaceholder = useCallback((receipt: AcademyReceipt) => {
    toast.success(`PDF download placeholder for ${receipt.receiptNumber}.`);
  }, []);

  return (
    <div className="max-w-screen-2xl mx-auto space-y-6">
      <div>
        <p className="text-xs font-700 uppercase tracking-[0.24em] text-primary">
          Academy Receipts
        </p>
        <h1 className="mt-1 text-2xl font-700 text-foreground">Receipts</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Receipt history generated from student fee payments.
        </p>
      </div>

      <div className="glass-card overflow-hidden rounded-2xl border border-border">
        <div className="grid gap-4 border-b border-border p-5 lg:grid-cols-[1fr_auto]">
          <div className="relative">
            <Search
              size={16}
              className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground"
            />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search by receipt number, student, course, or date"
              className="w-full rounded-xl border border-border bg-input py-3 pl-11 pr-4 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <select
            value={modeFilter}
            onChange={(event) => setModeFilter(event.target.value as 'all' | AcademyPaymentMode)}
            className="rounded-xl border border-border bg-input px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="all">All modes</option>
            <option value="cash">Cash</option>
            <option value="upi">UPI</option>
            <option value="bank">Bank</option>
            <option value="card">Card</option>
          </select>
        </div>

        {loading ? (
          showRetry ? (
            <div className="p-5">
              <RetryState onRetry={() => setRetryKey((current) => current + 1)} />
            </div>
          ) : (
            <div className="p-16 text-center text-muted-foreground">
              {showSlowMessage
                ? 'Network is slow. Trying to load your workspace.'
                : 'Loading receipts...'}
            </div>
          )
        ) : filteredReceipts.length === 0 ? (
          <div className="px-5 py-16 text-center">
            <p className="text-sm font-600 text-foreground">
              No fee records yet. Add a payment to generate receipts.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-muted/80 text-xs uppercase tracking-wider text-muted-foreground">
                <tr>
                  <th className="px-5 py-4">Receipt Number</th>
                  <th className="px-5 py-4">Student Name</th>
                  <th className="px-5 py-4">Course</th>
                  <th className="px-5 py-4">Amount Paid</th>
                  <th className="px-5 py-4">Pending Amount</th>
                  <th className="px-5 py-4">Payment Mode</th>
                  <th className="px-5 py-4">Payment Date</th>
                  <th className="px-5 py-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border bg-white">
                {filteredReceipts.map((receipt) => (
                  <tr key={receipt.id}>
                    <td className="px-5 py-4 font-600 text-foreground">{receipt.receiptNumber}</td>
                    <td className="px-5 py-4 text-muted-foreground">{receipt.studentName}</td>
                    <td className="px-5 py-4 text-muted-foreground">{receipt.courseName}</td>
                    <td className="px-5 py-4 text-muted-foreground">
                      {formatCurrency(receipt.amountPaid)}
                    </td>
                    <td className="px-5 py-4 text-muted-foreground">
                      {formatCurrency(receipt.pendingAmount)}
                    </td>
                    <td className="px-5 py-4 text-muted-foreground">{receipt.paymentMode}</td>
                    <td className="px-5 py-4 text-muted-foreground">{receipt.paymentDate}</td>
                    <td className="px-5 py-4">
                      <div className="flex justify-end gap-2">
                        <button
                          type="button"
                          onClick={() => setSelectedReceipt(receipt)}
                          className="btn-outline rounded-xl px-3 py-2 text-xs"
                        >
                          <Eye size={14} />
                        </button>
                        <button
                          type="button"
                          onClick={() => printReceipt(receipt)}
                          className="btn-outline rounded-xl px-3 py-2 text-xs"
                        >
                          <Printer size={14} />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownloadPlaceholder(receipt)}
                          className="btn-outline rounded-xl px-3 py-2 text-xs"
                        >
                          <Download size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {selectedReceipt && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm">
          <div className="mx-auto mt-10 max-w-3xl rounded-[28px] border border-border bg-white shadow-card">
            <div className="flex items-center justify-between border-b border-border px-6 py-5">
              <div>
                <p className="text-xs font-700 uppercase tracking-[0.22em] text-primary">
                  Receipt Preview
                </p>
                <h2 className="mt-1 text-xl font-700 text-foreground">
                  {selectedReceipt.receiptNumber}
                </h2>
              </div>
              <button
                type="button"
                onClick={() => setSelectedReceipt(null)}
                className="btn-outline rounded-xl px-4 py-2 text-sm"
              >
                Close
              </button>
            </div>

            <div className="space-y-6 p-6">
              <div className="rounded-2xl border border-border bg-muted/20 p-5">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <p className="text-lg font-700 text-foreground">
                      {selectedReceipt.businessName}
                    </p>
                    <p className="mt-1 text-sm text-muted-foreground">
                      {selectedReceipt.businessAddress || 'Business address not added'}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      {selectedReceipt.businessPhone || 'Business phone not added'}
                    </p>
                  </div>
                  <div className="text-left sm:text-right">
                    <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">
                      Payment Date
                    </p>
                    <p className="mt-1 text-sm font-600 text-foreground">
                      {selectedReceipt.paymentDate}
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                {[
                  ['Student Name', selectedReceipt.studentName],
                  ['Course', selectedReceipt.courseName],
                  ['Payment Mode', selectedReceipt.paymentMode],
                  ['Receipt ID', selectedReceipt.receiptId],
                ].map(([label, value]) => (
                  <div key={label} className="rounded-2xl border border-border p-4">
                    <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">
                      {label}
                    </p>
                    <p className="mt-2 text-sm font-600 text-foreground">{value}</p>
                  </div>
                ))}
              </div>

              <div className="rounded-2xl border border-border p-5">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Amount Paid</span>
                  <strong className="text-foreground">
                    {formatCurrency(selectedReceipt.amountPaid)}
                  </strong>
                </div>
                <div className="mt-3 flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Pending Amount</span>
                  <strong className="text-foreground">
                    {formatCurrency(selectedReceipt.pendingAmount)}
                  </strong>
                </div>
              </div>

              <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
                <button
                  type="button"
                  onClick={() => handleDownloadPlaceholder(selectedReceipt)}
                  className="btn-outline rounded-xl px-5 py-3 text-sm"
                >
                  Download
                </button>
                <button
                  type="button"
                  onClick={() => printReceipt(selectedReceipt)}
                  className="btn-primary rounded-xl px-5 py-3 text-sm"
                >
                  Print Receipt
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
